const NS_SYSTEM_SERVICES = "systemServices";
const SET_LOADING_SYSTEM_SERVICES = `${NS_SYSTEM_SERVICES}/setLoadingSystemServices`;
const GET_ALL_SYSTEM_SERVICES = `${NS_SYSTEM_SERVICES}/getAllSystemServices`;
const SAVE_ALL_SYSTEM_SERVICES = `${NS_SYSTEM_SERVICES}/saveAllSystemServices`;
const CREATE_SYSTEM_SERVICES = `${NS_SYSTEM_SERVICES}/createSystemServices`;
const GET_DETAIL_SYSTEM_SERVICES = `${NS_SYSTEM_SERVICES}/getDetailSystemServices`;
const SAVE_DETAIL_SYSTEM_SERVICES = `${NS_SYSTEM_SERVICES}/saveAllSystemServices`;
const UPDATE_SYSTEM_SERVICES = `${NS_SYSTEM_SERVICES}/updateSystemServices`;
const DELETE_SYSTEM_SERVICES = `${NS_SYSTEM_SERVICES}/deleteSystemServices`;

export {
  SET_LOADING_SYSTEM_SERVICES,
  GET_ALL_SYSTEM_SERVICES,
  SAVE_ALL_SYSTEM_SERVICES,
  CREATE_SYSTEM_SERVICES,
  GET_DETAIL_SYSTEM_SERVICES,
  SAVE_DETAIL_SYSTEM_SERVICES,
  UPDATE_SYSTEM_SERVICES,
  DELETE_SYSTEM_SERVICES,
};
