const NS_BOOKING_SERVICES = "bookingServices";
const SET_LOADING_BOOKING_SERVICES = `${NS_BOOKING_SERVICES}/setLoadingBookingServices`;
const GET_ALL_BOOKING_SERVICES = `${NS_BOOKING_SERVICES}/getAllBookingServices`;
const SAVE_ALL_BOOKING_SERVICES = `${NS_BOOKING_SERVICES}/saveAllBookingServices`;
const GET_DETAIL_BOOKING_SERVICES = `${NS_BOOKING_SERVICES}/getDetailBookingServices`;
const SAVE_DETAIL_BOOKING_SERVICES = `${NS_BOOKING_SERVICES}/saveDetailBookingServices`;
export {
  SET_LOADING_BOOKING_SERVICES,
  GET_ALL_BOOKING_SERVICES,
  SAVE_ALL_BOOKING_SERVICES,
  GET_DETAIL_BOOKING_SERVICES,
  SAVE_DETAIL_BOOKING_SERVICES,
};
